# ── Julia-side @ccallable wrapper generation ──────────────────────────
#
# For each exported function we emit a `Base.@ccallable` wrapper whose argument
# and return types are the C-ABI carrier types. The wrapper converts incoming
# carriers to native values (`from_c`), calls the user function, and converts the
# result back (`to_c`). For scalars these conversions are the identity, so the
# wrapper compiles down to a direct call.
#
# Wrappers are generated as Julia *source text* because they are `include`d by
# juliac in a separate build process (see build.jl).

# A type rendered as parseable Julia source valid inside the generated entry
# (which only does `using ParselTongue`). Scalars/String/Cstring print back
# directly; the ParselTongue-owned carrier `PtBuffer{T}` is module-qualified.
function _type_src(@nospecialize(T::Type))
    if T isa DataType && T.name === PtBuffer.body.name
        return string("ParselTongue.PtBuffer{", _type_src(T.parameters[1]), "}")
    end
    return string(T)
end

"""
    emit_ccallable(e::PtExport) -> String

Return the Julia source for the `Base.@ccallable` wrapper exporting `e`. The
wrapper references the user function by its bare name, so it must be emitted into
the same scope into which the user code was `include`d.
"""
function emit_ccallable(e::PtExport)
    sym       = cabi_symbol(e)                       # e.g. "pt_add"
    ret_c     = c_abi_type(e.ret)
    # Parameter list with carrier types: `a::Int64, b::Int64`
    params = String[]
    conv   = String[]
    for a in e.args
        ci = c_abi_type(a.jl_type)
        push!(params, string(a.name, "::", _type_src(ci)))
        # from_c(<NativeType>, <param>)
        push!(conv, string("ParselTongue.from_c(", _type_src(a.jl_type), ", ", a.name, ")"))
    end
    call = string(e.jl_func, "(", join(conv, ", "), ")")
    body = string("ParselTongue.to_c(", call, ")")
    return string(
        "Base.@ccallable function ", sym, "(", join(params, ", "), ")::", _type_src(ret_c), "\n",
        "    return ", body, "\n",
        "end\n",
    )
end

"""
    emit_entry(exports, user_path) -> String

Return the full source of the juliac entry file: load ParselTongue, `include`
the user's source, then define every `@ccallable` wrapper. `user_path` must be
absolute (juliac's buildscript resolves includes relative to itself otherwise).
"""
function emit_entry(exports::AbstractVector{PtExport}, user_path::AbstractString)
    io = IOBuffer()
    println(io, "# Generated by ParselTongue — do not edit.")
    println(io, "using ParselTongue")
    println(io, "include(", repr(abspath(user_path)), ")")
    println(io)
    for e in exports
        println(io, emit_ccallable(e))
    end
    return String(take!(io))
end
